pluginManagement {
    plugins {
        kotlin("jvm") version "2.2.0"
    }
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}
/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "BCU-java-PC"
